font_family 			MonoLisa
font_size  				12.0
adjust_line_height  	140%

symbol_map codepoints 3270Medium Nerd Font Mono
narrow_symbols codepoints 3

window_padding_width 	0
window_margin_width 	0
window_border_width 	0
single_window_margin_width -1
draw_minimal_borders 	yes
hide_window_decorations titlebar-only
placement_strategy 		top-left
resize_in_steps yes

tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style separator
tab_bar_min_tabs 1
tab_title_template " {bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title} "
active_tab_font_style   bold
inactive_tab_font_style   italic
tab_separator ""
tab_bar_align left

# TokyoNight
background #1a1b26
foreground #c0caf5
selection_background #33467C
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #1f2335
inactive_tab_background #000000
inactive_tab_foreground #c0caf5
tab_bar_background #000000

# normal
color0 #15161E
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b
