# Fonts
font_family    	    MonoLisa
symbol_map codepoints 3270Medium Nerd Font Mono
disable_ligatures   cursor

# Font size
font_size 13.0
adjust_line_height  8
# adjust_column_width 112%

# Layout
remember_window_size  yes

# Tabs
tab_bar_style                   custom
tab_separator                   ""
tab_fade                        0 0 0 0
tab_title_template              "{fmt.fg._5C6773}{fmt.bg.default} {index}:{f'{title[:8]}…{title[-8:]}' if title.rindex(title[-1]) + 1 > 19 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "{fmt.fg._ffffff}{fmt.bg.default} {index}:{f'{title[:8]}…{title[-8:]}' if title.rindex(title[-1]) + 1 > 19 else title}{' []' if layout_name == 'stack' else ''} "
tab_activity_symbol             none
tab_bar_edge                    top
tab_bar_margin_height           0.0 0.0
active_tab_font_style           bold-italic
inactive_tab_font_style         normal
tab_bar_min_tabs                2
bell_on_tab                     no

# Color scheme
foreground #d4d4d4
background #12131b
cursor #d16cfe
selection_background #343f4c
color0 #191e2a
color8 #686868
color1 #ed8274
color9 #f28779
color2  #a6cc70
color10 #bae67e
color3  #fad07b
color11 #ffd580
color4  #6dcbfa
color12 #73d0ff
color5  #cfbafa
color13 #d4bfff
color6  #90e1c6
color14 #95e6cb
color7  #c7c7c7
color15 #ffffff
selection_foreground #212733

# OS-Specific
macos_titlebar_color background
macos_option_as_alt left
macos_thicken_font 0.2

# Keyboard maps
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
