# Set prefix to Ctrl+Space
set -g prefix C-a

# Set TERM variable
set -g default-terminal "wezterm"

# Fix vim Escape
set -s escape-time 0

# Enable mouse
setw -g mouse on

# Set terminal title
set -g set-titles on
set -g set-titles-string "#{session_name}"
set -g pane-border-status top
set-hook -g window-layout-changed 'set-window -F pane-border-status "#{?#{==:#{window_panes},1},off,#{?#{window_zoomed_flag},off,top}}"'
set -g pane-border-format "#{?pane_active,#[bold],} #{pane_current_command} #F "

# Highlight windows with a visual bell
setw -g monitor-bell on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Set default main pane height
set-window-option -g main-pane-height '70%' 

# Set fish as shell
set -g default-command /bin/zsh
set -g default-shell /bin/zsh

# Fix home and end in vim
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Smart pane switching with awareness of Vim splits.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
| grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|[nl]?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# vim-tpipeline
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 90
set -g status-right-length 90
set -g status-justify absolute-centre

# Status bar
# set -g status-right-length 0
# set -g status-left-length 30
# set -g status-style bg=default
# set -g window-status-separator ""

# Session name 
# set -g status-left "#[fg=brightwhite,bg=default,bold]  #S #[fg=brightwhite,bg=default,nobold] "
# set -g status-right ""

# Windows
set -g @session-name "#[fg=#565f89]#{?#{==:#{window_index},1},  #{?#{window_zoomed_flag},-Z ,}#{=/12/…:session_name} ,}"
set -g @window-name "#[fg=#{?#{window_active},default,#565f89}]#I:#W"
set -g @space-after "#{?#{==:#{window_index},#{session_windows}}, ,}"
set -g @status "#{E:@session-name}#{?#{==:#{session_windows},1},,#{E:@window-name}}#{E:@space-after}"
set -g window-status-current-format "#{E:@status}"
set -g window-status-format "#{E:@status}"

# Borders
set -g pane-border-style fg=blue
set -g pane-active-border-style fg=magenta
