source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "HeavyRain266/tokyonight.kak" theme config %{
    colorscheme tokyonight
}

plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
}

plug "andreyorst/fzf.kak" config %{
    map -docstring 'fzf mode' global normal '<c-p>' ': fzf-mode<ret>'
}
